package httpx

import (
	"net/http"
	"strings"
)

// Preflight response policy. These are constants rather than environment variables
// because every knob is a support question and nothing in the roadmap needs to tune
// them.
const (
	// Exactly the methods the mux registers. Advertising capability the server does
	// not have is misleading; HEAD is CORS-safelisted and needs no listing.
	allowMethods = "GET, POST, OPTIONS"

	// Content-Type is required for the JSON-bodied route and voice-token endpoints,
	// which are preflighted precisely because of that header. Authorization is listed
	// ahead of need so that adding auth later does not present as a baffling preflight
	// failure. Deliberately a static contract rather than a reflection of
	// Access-Control-Request-Headers: the server should allow what it was designed to
	// allow, not whatever it is asked to allow.
	allowHeaders = "Content-Type, Authorization"

	// 10 minutes. Long enough to spare a round-trip before each preflighted request on
	// mobile data, short enough that an ALLOWED_ORIGINS change takes effect promptly —
	// a long max-age caches per (origin, path, method, header set) and produces
	// "I fixed the config but it's still broken". Well under Chrome's 7200s cap, so the
	// advertised value is the honoured one.
	maxAge = "600"
)

// ParseOrigins splits a comma-separated ALLOWED_ORIGINS value into a list of origins.
//
// Entries are trimmed of surrounding whitespace and empty entries are dropped, so
// "a, b", "a,b" and "a,,b," all parse identically. Nothing else is normalised:
// matching is exact string equality (see CORS), which is what makes it impossible for
// a request-supplied origin to reach a response header unless an operator wrote that
// exact string into the configuration.
//
// A value that is empty, or contains only separators and whitespace, yields an empty
// slice — which CORS reads as "allow every origin".
func ParseOrigins(raw string) []string {
	if raw == "" {
		return nil
	}
	parts := strings.Split(raw, ",")
	origins := make([]string, 0, len(parts))
	for _, p := range parts {
		if p = strings.TrimSpace(p); p != "" {
			origins = append(origins, p)
		}
	}
	if len(origins) == 0 {
		return nil
	}
	return origins
}

// CORS returns middleware that applies the browser cross-origin policy to every
// response, and answers browser preflight requests without consulting the mux.
//
// It wraps the whole mux rather than individual handlers so that a route added later
// cannot forget it, and so that responses generated by the mux itself (404, 405) and
// by any outer recovery middleware (500) still carry the headers a browser needs in
// order to surface them. That is why the headers are set *before* delegating.
//
// An empty origins slice allows every origin. The caller is responsible for warning
// about that at startup; it is a deliberate zero-config default for local development
// (the dev page is reachable as localhost, 127.0.0.1 and a DHCP-assigned LAN address,
// which are three separate origins) and must be visibly unsafe anywhere else.
//
// A disallowed origin on a non-preflight request is *not* rejected: the request runs
// and the response simply carries no Access-Control-Allow-Origin, which is precisely
// how CORS refuses. Rejecting server-side would stop no attacker — CORS is enforced by
// the browser, on the response, and a non-browser client never asks — while breaking
// every legitimate caller that sends no Origin at all: the native client, curl,
// wstest.mjs, and platform health checks. Server-side origin enforcement belongs on
// the WebSocket path, in the upgrader's CheckOrigin, where the live location data
// actually flows and where CORS does not apply.
//
// Access-Control-Allow-Credentials is never sent. There are no cookies and no
// sessions; rider identity travels as a query parameter. Sending it while the
// permissive default is active would let any site make authenticated requests the
// moment authentication exists.
func CORS(origins []string) func(http.Handler) http.Handler {
	// Built once, at startup. The request path does no parsing and no allocation
	// beyond the response headers themselves.
	allowAll := len(origins) == 0
	allowed := make(map[string]struct{}, len(origins))
	for _, o := range origins {
		allowed[o] = struct{}{}
	}

	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			// Unconditional, including on responses that carry no
			// Access-Control-Allow-Origin. The header value depends on the request's
			// Origin, so any shared cache — a service worker, or the reverse proxy this
			// will be deployed behind — could otherwise replay one origin's response to
			// another. A cached header-less response is the harder half of that bug.
			w.Header().Add("Vary", "Origin")

			origin := r.Header.Get("Origin")

			// The presence of Access-Control-Request-Method is the Fetch spec's
			// definitive marker of a preflight; no other request carries it. Guarding on
			// it keeps this middleware's contract narrow: a plain OPTIONS falls through
			// to the mux and keeps net/http's 405 + Allow behaviour, rather than every
			// path on the server answering 204.
			isPreflight := r.Method == http.MethodOptions && r.Header.Get("Access-Control-Request-Method") != ""

			if origin == "" {
				// No Origin: a native client, curl, a monitor, or a same-origin request.
				// None of them are subject to CORS, so there is nothing to add and
				// nothing to refuse.
				if isPreflight {
					w.WriteHeader(http.StatusNoContent)
					return
				}
				next.ServeHTTP(w, r)
				return
			}

			_, ok := allowed[origin]
			if allowAll {
				ok = true
			}
			if ok {
				// Echo the matched origin rather than "*". One code path for both modes,
				// and it stays compatible with credentials should they ever be needed —
				// "*" is not. Safe against header injection precisely because the value
				// echoed is one that compared equal to an operator-supplied entry.
				w.Header().Set("Access-Control-Allow-Origin", origin)
			}

			if isPreflight {
				if !ok {
					http.Error(w, "origin not allowed", http.StatusForbidden)
					return
				}
				w.Header().Set("Access-Control-Allow-Methods", allowMethods)
				w.Header().Set("Access-Control-Allow-Headers", allowHeaders)
				w.Header().Set("Access-Control-Max-Age", maxAge)
				// Terminate here. The mux registers no OPTIONS pattern, so it would
				// answer 405 for a path it knows — and a 405 is a failed preflight, which
				// would make every JSON-bodied endpoint unreachable from a browser.
				w.WriteHeader(http.StatusNoContent)
				return
			}

			next.ServeHTTP(w, r)
		})
	}
}
